# Generated by Django 4.1 on 2023-01-19 13:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0002_blog_location_blog_status_ngo_description_ngo_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
