# Generated by Django 4.1 on 2023-02-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0003_alter_ngo_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-published',)},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='status',
        ),
        migrations.AddField(
            model_name='blog',
            name='published',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=50),
        ),
    ]
