# Generated by Django 4.1 on 2023-02-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0004_alter_blog_options_remove_blog_status_blog_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Blogpic'),
        ),
    ]
